"""empty message

Revision ID: 2193d15cae6c
Revises: 
Create Date: 2020-06-10 14:36:18.330403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2193d15cae6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Actors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Movies', 'release',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Movies', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Movies', 'release',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actors', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
