"""empty message

Revision ID: b1da8c83f305
Revises: 2193d15cae6c
Create Date: 2020-06-18 16:31:06.554733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1da8c83f305'
down_revision = '2193d15cae6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actors', sa.Column('image_link', sa.String(), nullable=True))
    op.add_column('Movies', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Movies', 'image_link')
    op.drop_column('Actors', 'image_link')
    # ### end Alembic commands ###
